// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: medias.sql

package sqlcgen

import (
	"context"
)

const countMedias = `-- name: CountMedias :one
SELECT COUNT(*)
FROM medias
`

func (q *Queries) CountMedias(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMedias)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :exec
INSERT INTO medias
(id, path, type, title, mime_type, size, created_at, updated_at)
VALUES($1, $2, $3, $4, $5, $6, NOW(), NOW())
`

type CreateMediaParams struct {
	ID       string
	Path     string
	Type     string
	Title    string
	MimeType string
	Size     int32
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) error {
	_, err := q.db.Exec(ctx, createMedia,
		arg.ID,
		arg.Path,
		arg.Type,
		arg.Title,
		arg.MimeType,
		arg.Size,
	)
	return err
}

const deleteMediaByID = `-- name: DeleteMediaByID :one
DELETE FROM medias
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteMediaByID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteMediaByID, id)
	err := row.Scan(&id)
	return id, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, created_at, updated_at, title, path, type, mime_type, size
FROM medias
WHERE id = $1
`

func (q *Queries) GetMediaByID(ctx context.Context, id string) (Media, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Media
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Path,
		&i.Type,
		&i.MimeType,
		&i.Size,
	)
	return i, err
}

const listMedias = `-- name: ListMedias :many
SELECT id, created_at, updated_at, title, path, type, mime_type, size
FROM medias
LIMIT $1 OFFSET $2
`

type ListMediasParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListMedias(ctx context.Context, arg ListMediasParams) ([]Media, error) {
	rows, err := q.db.Query(ctx, listMedias, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Media
	for rows.Next() {
		var i Media
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Path,
			&i.Type,
			&i.MimeType,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaByID = `-- name: UpdateMediaByID :one
UPDATE medias
SET title = $2, updated_at = NOW()
WHERE id = $1
RETURNING id
`

type UpdateMediaByIDParams struct {
	ID    string
	Title string
}

func (q *Queries) UpdateMediaByID(ctx context.Context, arg UpdateMediaByIDParams) (string, error) {
	row := q.db.QueryRow(ctx, updateMediaByID, arg.ID, arg.Title)
	var id string
	err := row.Scan(&id)
	return id, err
}
