// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: protofiles/media_service.proto

package mediapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_UNKNOWN MediaType = 0
	MediaType_IMAGE   MediaType = 1
	MediaType_VIDEO   MediaType = 2
	MediaType_AUDIO   MediaType = 3
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "UNKNOWN",
		1: "IMAGE",
		2: "VIDEO",
		3: "AUDIO",
	}
	MediaType_value = map[string]int32{
		"UNKNOWN": 0,
		"IMAGE":   1,
		"VIDEO":   2,
		"AUDIO":   3,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_protofiles_media_service_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_protofiles_media_service_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{0}
}

type CreateMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaRequest) Reset() {
	*x = CreateMediaRequest{}
	mi := &file_protofiles_media_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaRequest) ProtoMessage() {}

func (x *CreateMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_media_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaRequest.ProtoReflect.Descriptor instead.
func (*CreateMediaRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{0}
}

type CreateMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	PresignedUrl  string                 `protobuf:"bytes,2,opt,name=presigned_url,json=presignedUrl,proto3" json:"presigned_url,omitempty"`
	FormData      map[string]string      `protobuf:"bytes,3,rep,name=form_data,json=formData,proto3" json:"form_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMediaResponse) Reset() {
	*x = CreateMediaResponse{}
	mi := &file_protofiles_media_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMediaResponse) ProtoMessage() {}

func (x *CreateMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_media_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMediaResponse.ProtoReflect.Descriptor instead.
func (*CreateMediaResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMediaResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CreateMediaResponse) GetPresignedUrl() string {
	if x != nil {
		return x.PresignedUrl
	}
	return ""
}

func (x *CreateMediaResponse) GetFormData() map[string]string {
	if x != nil {
		return x.FormData
	}
	return nil
}

type GetMediaByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaByIDRequest) Reset() {
	*x = GetMediaByIDRequest{}
	mi := &file_protofiles_media_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaByIDRequest) ProtoMessage() {}

func (x *GetMediaByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_media_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMediaByIDRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaByIDRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Type          MediaType              `protobuf:"varint,6,opt,name=type,proto3,enum=mediapb.MediaType" json:"type,omitempty"`
	MimeType      string                 `protobuf:"bytes,7,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Size          int64                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_protofiles_media_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_media_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{3}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Media) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Media) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Media) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Media) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_UNKNOWN
}

func (x *Media) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Media) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMediasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediasRequest) Reset() {
	*x = ListMediasRequest{}
	mi := &file_protofiles_media_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediasRequest) ProtoMessage() {}

func (x *ListMediasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_media_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediasRequest.ProtoReflect.Descriptor instead.
func (*ListMediasRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListMediasRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMediasRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MediaList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Media               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaList) Reset() {
	*x = MediaList{}
	mi := &file_protofiles_media_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaList) ProtoMessage() {}

func (x *MediaList) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_media_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaList.ProtoReflect.Descriptor instead.
func (*MediaList) Descriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{5}
}

func (x *MediaList) GetList() []*Media {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *MediaList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MediaList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MediaList) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateMediaByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMediaByIDRequest) Reset() {
	*x = UpdateMediaByIDRequest{}
	mi := &file_protofiles_media_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaByIDRequest) ProtoMessage() {}

func (x *UpdateMediaByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_media_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMediaByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateMediaByIDRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMediaByIDRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *UpdateMediaByIDRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteMediaByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaByIDRequest) Reset() {
	*x = DeleteMediaByIDRequest{}
	mi := &file_protofiles_media_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaByIDRequest) ProtoMessage() {}

func (x *DeleteMediaByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_media_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaByIDRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_media_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMediaByIDRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

var File_protofiles_media_service_proto protoreflect.FileDescriptor

const file_protofiles_media_service_proto_rawDesc = "" +
	"\n" +
	"\x1eprotofiles/media_service.proto\x12\amediapb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x14\n" +
	"\x12CreateMediaRequest\"\xdb\x01\n" +
	"\x13CreateMediaResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12#\n" +
	"\rpresigned_url\x18\x02 \x01(\tR\fpresignedUrl\x12G\n" +
	"\tform_data\x18\x03 \x03(\v2*.mediapb.CreateMediaResponse.FormDataEntryR\bformData\x1a;\n" +
	"\rFormDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"0\n" +
	"\x13GetMediaByIDRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\x90\x02\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\x12&\n" +
	"\x04type\x18\x06 \x01(\x0e2\x12.mediapb.MediaTypeR\x04type\x12\x1b\n" +
	"\tmime_type\x18\a \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\b \x01(\x03R\x04size\"A\n" +
	"\x11ListMediasRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"s\n" +
	"\tMediaList\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.mediapb.MediaR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"I\n" +
	"\x16UpdateMediaByIDRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"3\n" +
	"\x16DeleteMediaByIDRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId*9\n" +
	"\tMediaType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05IMAGE\x10\x01\x12\t\n" +
	"\x05VIDEO\x10\x02\x12\t\n" +
	"\x05AUDIO\x10\x032\xec\x02\n" +
	"\fMediaService\x12H\n" +
	"\vCreateMedia\x12\x1b.mediapb.CreateMediaRequest\x1a\x1c.mediapb.CreateMediaResponse\x12<\n" +
	"\fGetMediaByID\x12\x1c.mediapb.GetMediaByIDRequest\x1a\x0e.mediapb.Media\x12<\n" +
	"\n" +
	"ListMedias\x12\x1a.mediapb.ListMediasRequest\x1a\x12.mediapb.MediaList\x12J\n" +
	"\x0fUpdateMediaByID\x12\x1f.mediapb.UpdateMediaByIDRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0fDeleteMediaByID\x12\x1f.mediapb.DeleteMediaByIDRequest\x1a\x16.google.protobuf.EmptyB\x1bZ\x19shared/pb/mediapb;mediapbb\x06proto3"

var (
	file_protofiles_media_service_proto_rawDescOnce sync.Once
	file_protofiles_media_service_proto_rawDescData []byte
)

func file_protofiles_media_service_proto_rawDescGZIP() []byte {
	file_protofiles_media_service_proto_rawDescOnce.Do(func() {
		file_protofiles_media_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protofiles_media_service_proto_rawDesc), len(file_protofiles_media_service_proto_rawDesc)))
	})
	return file_protofiles_media_service_proto_rawDescData
}

var file_protofiles_media_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protofiles_media_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_protofiles_media_service_proto_goTypes = []any{
	(MediaType)(0),                 // 0: mediapb.MediaType
	(*CreateMediaRequest)(nil),     // 1: mediapb.CreateMediaRequest
	(*CreateMediaResponse)(nil),    // 2: mediapb.CreateMediaResponse
	(*GetMediaByIDRequest)(nil),    // 3: mediapb.GetMediaByIDRequest
	(*Media)(nil),                  // 4: mediapb.Media
	(*ListMediasRequest)(nil),      // 5: mediapb.ListMediasRequest
	(*MediaList)(nil),              // 6: mediapb.MediaList
	(*UpdateMediaByIDRequest)(nil), // 7: mediapb.UpdateMediaByIDRequest
	(*DeleteMediaByIDRequest)(nil), // 8: mediapb.DeleteMediaByIDRequest
	nil,                            // 9: mediapb.CreateMediaResponse.FormDataEntry
	(*timestamppb.Timestamp)(nil),  // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_protofiles_media_service_proto_depIdxs = []int32{
	9,  // 0: mediapb.CreateMediaResponse.form_data:type_name -> mediapb.CreateMediaResponse.FormDataEntry
	10, // 1: mediapb.Media.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: mediapb.Media.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: mediapb.Media.type:type_name -> mediapb.MediaType
	4,  // 4: mediapb.MediaList.list:type_name -> mediapb.Media
	1,  // 5: mediapb.MediaService.CreateMedia:input_type -> mediapb.CreateMediaRequest
	3,  // 6: mediapb.MediaService.GetMediaByID:input_type -> mediapb.GetMediaByIDRequest
	5,  // 7: mediapb.MediaService.ListMedias:input_type -> mediapb.ListMediasRequest
	7,  // 8: mediapb.MediaService.UpdateMediaByID:input_type -> mediapb.UpdateMediaByIDRequest
	8,  // 9: mediapb.MediaService.DeleteMediaByID:input_type -> mediapb.DeleteMediaByIDRequest
	2,  // 10: mediapb.MediaService.CreateMedia:output_type -> mediapb.CreateMediaResponse
	4,  // 11: mediapb.MediaService.GetMediaByID:output_type -> mediapb.Media
	6,  // 12: mediapb.MediaService.ListMedias:output_type -> mediapb.MediaList
	11, // 13: mediapb.MediaService.UpdateMediaByID:output_type -> google.protobuf.Empty
	11, // 14: mediapb.MediaService.DeleteMediaByID:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_protofiles_media_service_proto_init() }
func file_protofiles_media_service_proto_init() {
	if File_protofiles_media_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protofiles_media_service_proto_rawDesc), len(file_protofiles_media_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_media_service_proto_goTypes,
		DependencyIndexes: file_protofiles_media_service_proto_depIdxs,
		EnumInfos:         file_protofiles_media_service_proto_enumTypes,
		MessageInfos:      file_protofiles_media_service_proto_msgTypes,
	}.Build()
	File_protofiles_media_service_proto = out.File
	file_protofiles_media_service_proto_goTypes = nil
	file_protofiles_media_service_proto_depIdxs = nil
}
