templates:
  service: std
  application: std
  infrastructure: std
  package: std

runners:
  api:
    env:
      - PORT=8080
      - DB_PATH=./tmp/db.sqlite
      - DB_AUTO_MIGRATE=true
    log:
      overwrite: true
