// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: series_service.proto

package seriespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TmdbId        string                 `protobuf:"bytes,3,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeriesRequest) Reset() {
	*x = CreateSeriesRequest{}
	mi := &file_series_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeriesRequest) ProtoMessage() {}

func (x *CreateSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeriesRequest.ProtoReflect.Descriptor instead.
func (*CreateSeriesRequest) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSeriesRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateSeriesRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateSeriesRequest) GetTmdbId() string {
	if x != nil {
		return x.TmdbId
	}
	return ""
}

type CreateSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      string                 `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSeriesResponse) Reset() {
	*x = CreateSeriesResponse{}
	mi := &file_series_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSeriesResponse) ProtoMessage() {}

func (x *CreateSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSeriesResponse.ProtoReflect.Descriptor instead.
func (*CreateSeriesResponse) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSeriesResponse) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

type GetSeriesByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      string                 `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesByIDRequest) Reset() {
	*x = GetSeriesByIDRequest{}
	mi := &file_series_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesByIDRequest) ProtoMessage() {}

func (x *GetSeriesByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesByIDRequest.ProtoReflect.Descriptor instead.
func (*GetSeriesByIDRequest) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetSeriesByIDRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	TmdbInfo      *TMDBInfo              `protobuf:"bytes,6,opt,name=tmdb_info,json=tmdbInfo,proto3" json:"tmdb_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_series_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{3}
}

func (x *Series) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Series) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Series) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Series) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Series) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Series) GetTmdbInfo() *TMDBInfo {
	if x != nil {
		return x.TmdbInfo
	}
	return nil
}

type TMDBInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *structpb.Struct       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TMDBInfo) Reset() {
	*x = TMDBInfo{}
	mi := &file_series_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TMDBInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TMDBInfo) ProtoMessage() {}

func (x *TMDBInfo) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TMDBInfo.ProtoReflect.Descriptor instead.
func (*TMDBInfo) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{4}
}

func (x *TMDBInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TMDBInfo) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSeriesRequest) Reset() {
	*x = ListSeriesRequest{}
	mi := &file_series_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSeriesRequest) ProtoMessage() {}

func (x *ListSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSeriesRequest.ProtoReflect.Descriptor instead.
func (*ListSeriesRequest) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListSeriesRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSeriesRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SeriesList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Series              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeriesList) Reset() {
	*x = SeriesList{}
	mi := &file_series_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeriesList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeriesList) ProtoMessage() {}

func (x *SeriesList) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeriesList.ProtoReflect.Descriptor instead.
func (*SeriesList) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{6}
}

func (x *SeriesList) GetList() []*Series {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SeriesList) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SeriesList) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SeriesList) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type UpdateSeriesByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      string                 `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TmdbId        string                 `protobuf:"bytes,4,opt,name=tmdb_id,json=tmdbId,proto3" json:"tmdb_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSeriesByIDRequest) Reset() {
	*x = UpdateSeriesByIDRequest{}
	mi := &file_series_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSeriesByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeriesByIDRequest) ProtoMessage() {}

func (x *UpdateSeriesByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeriesByIDRequest.ProtoReflect.Descriptor instead.
func (*UpdateSeriesByIDRequest) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSeriesByIDRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

func (x *UpdateSeriesByIDRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateSeriesByIDRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSeriesByIDRequest) GetTmdbId() string {
	if x != nil {
		return x.TmdbId
	}
	return ""
}

type DeleteSeriesByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesId      string                 `protobuf:"bytes,1,opt,name=series_id,json=seriesId,proto3" json:"series_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeriesByIDRequest) Reset() {
	*x = DeleteSeriesByIDRequest{}
	mi := &file_series_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeriesByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeriesByIDRequest) ProtoMessage() {}

func (x *DeleteSeriesByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_series_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeriesByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteSeriesByIDRequest) Descriptor() ([]byte, []int) {
	return file_series_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSeriesByIDRequest) GetSeriesId() string {
	if x != nil {
		return x.SeriesId
	}
	return ""
}

var File_series_service_proto protoreflect.FileDescriptor

const file_series_service_proto_rawDesc = "" +
	"\n" +
	"\x14series_service.proto\x12\bseriespb\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"f\n" +
	"\x13CreateSeriesRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\atmdb_id\x18\x03 \x01(\tR\x06tmdbId\"3\n" +
	"\x14CreateSeriesResponse\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\tR\bseriesId\"3\n" +
	"\x14GetSeriesByIDRequest\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\tR\bseriesId\"\xf7\x01\n" +
	"\x06Series\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12/\n" +
	"\ttmdb_info\x18\x06 \x01(\v2\x12.seriespb.TMDBInfoR\btmdbInfo\"G\n" +
	"\bTMDBInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\"A\n" +
	"\x11ListSeriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"v\n" +
	"\n" +
	"SeriesList\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.seriespb.SeriesR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x03R\x06offset\"\x87\x01\n" +
	"\x17UpdateSeriesByIDRequest\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\tR\bseriesId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\atmdb_id\x18\x04 \x01(\tR\x06tmdbId\"6\n" +
	"\x17DeleteSeriesByIDRequest\x12\x1b\n" +
	"\tseries_id\x18\x01 \x01(\tR\bseriesId2\x80\x03\n" +
	"\rSeriesService\x12M\n" +
	"\fCreateSeries\x12\x1d.seriespb.CreateSeriesRequest\x1a\x1e.seriespb.CreateSeriesResponse\x12A\n" +
	"\rGetSeriesByID\x12\x1e.seriespb.GetSeriesByIDRequest\x1a\x10.seriespb.Series\x12?\n" +
	"\n" +
	"ListSeries\x12\x1b.seriespb.ListSeriesRequest\x1a\x14.seriespb.SeriesList\x12M\n" +
	"\x10UpdateSeriesByID\x12!.seriespb.UpdateSeriesByIDRequest\x1a\x16.google.protobuf.Empty\x12M\n" +
	"\x10DeleteSeriesByID\x12!.seriespb.DeleteSeriesByIDRequest\x1a\x16.google.protobuf.EmptyB\x1dZ\x1bcommon/pb/seriespb;seriespbb\x06proto3"

var (
	file_series_service_proto_rawDescOnce sync.Once
	file_series_service_proto_rawDescData []byte
)

func file_series_service_proto_rawDescGZIP() []byte {
	file_series_service_proto_rawDescOnce.Do(func() {
		file_series_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_series_service_proto_rawDesc), len(file_series_service_proto_rawDesc)))
	})
	return file_series_service_proto_rawDescData
}

var file_series_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_series_service_proto_goTypes = []any{
	(*CreateSeriesRequest)(nil),     // 0: seriespb.CreateSeriesRequest
	(*CreateSeriesResponse)(nil),    // 1: seriespb.CreateSeriesResponse
	(*GetSeriesByIDRequest)(nil),    // 2: seriespb.GetSeriesByIDRequest
	(*Series)(nil),                  // 3: seriespb.Series
	(*TMDBInfo)(nil),                // 4: seriespb.TMDBInfo
	(*ListSeriesRequest)(nil),       // 5: seriespb.ListSeriesRequest
	(*SeriesList)(nil),              // 6: seriespb.SeriesList
	(*UpdateSeriesByIDRequest)(nil), // 7: seriespb.UpdateSeriesByIDRequest
	(*DeleteSeriesByIDRequest)(nil), // 8: seriespb.DeleteSeriesByIDRequest
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 10: google.protobuf.Struct
	(*emptypb.Empty)(nil),           // 11: google.protobuf.Empty
}
var file_series_service_proto_depIdxs = []int32{
	9,  // 0: seriespb.Series.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: seriespb.Series.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 2: seriespb.Series.tmdb_info:type_name -> seriespb.TMDBInfo
	10, // 3: seriespb.TMDBInfo.data:type_name -> google.protobuf.Struct
	3,  // 4: seriespb.SeriesList.list:type_name -> seriespb.Series
	0,  // 5: seriespb.SeriesService.CreateSeries:input_type -> seriespb.CreateSeriesRequest
	2,  // 6: seriespb.SeriesService.GetSeriesByID:input_type -> seriespb.GetSeriesByIDRequest
	5,  // 7: seriespb.SeriesService.ListSeries:input_type -> seriespb.ListSeriesRequest
	7,  // 8: seriespb.SeriesService.UpdateSeriesByID:input_type -> seriespb.UpdateSeriesByIDRequest
	8,  // 9: seriespb.SeriesService.DeleteSeriesByID:input_type -> seriespb.DeleteSeriesByIDRequest
	1,  // 10: seriespb.SeriesService.CreateSeries:output_type -> seriespb.CreateSeriesResponse
	3,  // 11: seriespb.SeriesService.GetSeriesByID:output_type -> seriespb.Series
	6,  // 12: seriespb.SeriesService.ListSeries:output_type -> seriespb.SeriesList
	11, // 13: seriespb.SeriesService.UpdateSeriesByID:output_type -> google.protobuf.Empty
	11, // 14: seriespb.SeriesService.DeleteSeriesByID:output_type -> google.protobuf.Empty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_series_service_proto_init() }
func file_series_service_proto_init() {
	if File_series_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_series_service_proto_rawDesc), len(file_series_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_series_service_proto_goTypes,
		DependencyIndexes: file_series_service_proto_depIdxs,
		MessageInfos:      file_series_service_proto_msgTypes,
	}.Build()
	File_series_service_proto = out.File
	file_series_service_proto_goTypes = nil
	file_series_service_proto_depIdxs = nil
}
