// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"time"
)

type Movie struct {
	ID          string
	CreatedAt   time.Time
	Title       string
	TmdbID      string
	Description string
}
