// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Episode struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	SeasonID    string
	Order       int64
	MediaID     string
}

type Media struct {
	ID          string
	CreatedAt   time.Time
	Path        string
	Type        string
	StorageType string
	MimeType    string
	Size        int64
}

type Movie struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	Title       string
	TmdbID      int64
	Description string
	MediaID     string
}

type Season struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	SeriesID    string
	Order       int64
}

type Series struct {
	ID          string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description string
	TmdbID      int64
}

type TmdbInfo struct {
	ID   string
	Data []byte
}
