http:
  routers:
    router-api-http:
      rule: "PathPrefix(`/api`)"
      entryPoints:
        - web
      service: service-bff
    router-api-https:
      rule: "PathPrefix(`/api`)"
      entryPoints:
        - websecure
      service: service-bff
      tls:
        certResolver: "my-resolver"

    router-doc-http:
      rule: "PathPrefix(`/doc`)"
      entryPoints:
        - web
      service: service-doc
      middlewares:
        - strip-doc
    router-doc-https:
      rule: "PathPrefix(`/doc`)"
      entryPoints:
        - websecure
      service: service-doc
      middlewares:
        - strip-doc
      tls:
        certResolver: "my-resolver"

  middlewares:
    strip-api:
      stripPrefix:
        prefixes:
          - "/api"
    strip-doc:
      stripPrefix:
        prefixes:
          - "/doc"

  services:
    service-bff:
      loadBalancer:
        servers:
          - url: "http://bff_service:8080/api"
    service-doc:
      loadBalancer:
        servers:
          - url: "http://apidoc:8080"
